-- BORRADO
DELETE FROM GKRPACT WHERE GKRPACT_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKRPRST WHERE GKRPRST_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKRRSQL WHERE GKRRSQL_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKRSQRP WHERE GKRSQRP_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKRSVBA WHERE GKRSVBA_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKRSQPA WHERE GKRSQPA_SQPR_CODE = 'GBA037_MDUU';
DELETE FROM GKVSQPA WHERE GKVSQPA_CODE LIKE 'GBA037_%';
DELETE FROM GKVSVBA WHERE GKVSVBA_CODE = 'GBA037_MDUU_A';
DELETE FROM GKVSQRU WHERE GKVSQRU_CODE = 'GBA037_MDUU_R';
--DELETE FROM GKRRLOG WHERE GKRRLOG_PRST_CODE = 'GBA037_MDUU_RS';
DELETE FROM GKVPRST WHERE GKVPRST_CODE = 'GBA037_MDUU_RS';
DELETE FROM GKVSQPR WHERE GKVSQPR_CODE = 'GBA037_MDUU';

COMMIT;
--PROCESO - Segunda y Tercera Matricula F_GBA037
Insert into GKVSQPR (GKVSQPR_CODE,GKVSQPR_DESC,GKVSQPR_SYS_REQ_IND,GKVSQPR_START_DATE,GKVSQPR_ACTIVITY_DATE,GKVSQPR_USER_ID,GKVSQPR_END_DATE,GKVSQPR_SURROGATE_ID,GKVSQPR_VERSION,GKVSQPR_DATA_ORIGIN,GKVSQPR_VPDI_CODE)
values ('GBA037_MDUU','GBA037 - Borrado Parcial/Total NRCs F','N',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);


--CONJUNTO DE REGLAS - GBA037_MDUU_RS
Insert into GKVPRST (GKVPRST_CODE,GKVPRST_DESC,GKVPRST_START_DATE,GKVPRST_ACTIVITY_DATE,GKVPRST_USER_ID,GKVPRST_END_DATE,GKVPRST_EXECUTE_BY,GKVPRST_SURROGATE_ID,GKVPRST_VERSION,GKVPRST_DATA_ORIGIN,GKVPRST_VPDI_CODE)
values ('GBA037_MDUU_RS','GBA037 - Borrado Parcial/Total NRCs F RuleSet',SYSDATE-1,SYSDATE-1,'SAISUSR',null,'ACTION',null,null,null,null);

--REGLA - GBA037_MDUU_R
Insert into GKVSQRU (GKVSQRU_CODE,GKVSQRU_DESC,GKVSQRU_SYS_REQ_IND,GKVSQRU_START_DATE,GKVSQRU_ACTIVITY_DATE,GKVSQRU_USER_ID,GKVSQRU_END_DATE,GKVSQRU_SURROGATE_ID,GKVSQRU_VERSION,GKVSQRU_DATA_ORIGIN,GKVSQRU_VPDI_CODE)
values ('GBA037_MDUU_R','GBA037 - Borrado Parcial/Total NRCs F Rule','N',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);

--ACCI�N GBA037_MDUU_A
Insert into GKVSVBA (GKVSVBA_CODE,GKVSVBA_DESC,GKVSVBA_SYS_REQ_IND,GKVSVBA_DBPROC_NAME,GKVSVBA_START_DATE,GKVSVBA_ACTIVITY_DATE,GKVSVBA_USER_ID,GKVSVBA_END_DATE,GKVSVBA_SURROGATE_ID,GKVSVBA_VERSION,GKVSVBA_DATA_ORIGIN,GKVSVBA_VPDI_CODE)
values ('GBA037_MDUU_A','GBA037 - Borrado Parcial/Total NRCs F - Action','N','TZKLSCL.f_execute_lc',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);

--PAR�METROS

Insert into GKVSQPA (GKVSQPA_CODE,GKVSQPA_DESC,GKVSQPA_DATA_TYPE_CDE,GKVSQPA_START_DATE,GKVSQPA_ACTIVITY_DATE,GKVSQPA_USER_ID,GKVSQPA_END_DATE,GKVSQPA_SURROGATE_ID,GKVSQPA_VERSION,GKVSQPA_DATA_ORIGIN,GKVSQPA_VPDI_CODE) values ('GBA037_1_ID','ID (Obligatorio)','C',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);
Insert into GKVSQPA (GKVSQPA_CODE,GKVSQPA_DESC,GKVSQPA_DATA_TYPE_CDE,GKVSQPA_START_DATE,GKVSQPA_ACTIVITY_DATE,GKVSQPA_USER_ID,GKVSQPA_END_DATE,GKVSQPA_SURROGATE_ID,GKVSQPA_VERSION,GKVSQPA_DATA_ORIGIN,GKVSQPA_VPDI_CODE) values ('GBA037_2_TERM','PERIODO (Obligatorio)','C',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);
Insert into GKVSQPA (GKVSQPA_CODE,GKVSQPA_DESC,GKVSQPA_DATA_TYPE_CDE,GKVSQPA_START_DATE,GKVSQPA_ACTIVITY_DATE,GKVSQPA_USER_ID,GKVSQPA_END_DATE,GKVSQPA_SURROGATE_ID,GKVSQPA_VERSION,GKVSQPA_DATA_ORIGIN,GKVSQPA_VPDI_CODE) values ('GBA037_3_CAMP','CAMPUS (Obligatorio)','C',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);
Insert into GKVSQPA (GKVSQPA_CODE,GKVSQPA_DESC,GKVSQPA_DATA_TYPE_CDE,GKVSQPA_START_DATE,GKVSQPA_ACTIVITY_DATE,GKVSQPA_USER_ID,GKVSQPA_END_DATE,GKVSQPA_SURROGATE_ID,GKVSQPA_VERSION,GKVSQPA_DATA_ORIGIN,GKVSQPA_VPDI_CODE) values ('GBA037_4_TIPO','EXCLUIR TIPO ALUMNO (Obligatorio)','C',SYSDATE-1,SYSDATE-1,'SAISUSR',null,null,null,null,null);


--ASIGNA PAR�METROS AL PROCESO
Insert into GKRSQPA (GKRSQPA_SQPR_CODE,GKRSQPA_SQPA_CODE,GKRSQPA_SYS_REQ_IND,GKRSQPA_ACTIVITY_DATE,GKRSQPA_USER_ID,GKRSQPA_SURROGATE_ID,GKRSQPA_VERSION,GKRSQPA_DATA_ORIGIN,GKRSQPA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_1_ID','N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQPA (GKRSQPA_SQPR_CODE,GKRSQPA_SQPA_CODE,GKRSQPA_SYS_REQ_IND,GKRSQPA_ACTIVITY_DATE,GKRSQPA_USER_ID,GKRSQPA_SURROGATE_ID,GKRSQPA_VERSION,GKRSQPA_DATA_ORIGIN,GKRSQPA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_2_TERM','N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQPA (GKRSQPA_SQPR_CODE,GKRSQPA_SQPA_CODE,GKRSQPA_SYS_REQ_IND,GKRSQPA_ACTIVITY_DATE,GKRSQPA_USER_ID,GKRSQPA_SURROGATE_ID,GKRSQPA_VERSION,GKRSQPA_DATA_ORIGIN,GKRSQPA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_3_CAMP','N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQPA (GKRSQPA_SQPR_CODE,GKRSQPA_SQPA_CODE,GKRSQPA_SYS_REQ_IND,GKRSQPA_ACTIVITY_DATE,GKRSQPA_USER_ID,GKRSQPA_SURROGATE_ID,GKRSQPA_VERSION,GKRSQPA_DATA_ORIGIN,GKRSQPA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_4_TIPO','N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);


--ASIGNA PAR�METROS A ACCI�N
Insert into GKRSVBA (GKRSVBA_SQPR_CODE,GKRSVBA_SVBA_CODE,GKRSVBA_SQPA_CODE,GKRSVBA_DEFAULT_VALUE,GKRSVBA_SYS_REQ_IND,GKRSVBA_ACTIVITY_DATE,GKRSVBA_USER_ID,GKRSVBA_SURROGATE_ID,GKRSVBA_VERSION,GKRSVBA_DATA_ORIGIN,GKRSVBA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_A','GBA037_1_ID',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSVBA (GKRSVBA_SQPR_CODE,GKRSVBA_SVBA_CODE,GKRSVBA_SQPA_CODE,GKRSVBA_DEFAULT_VALUE,GKRSVBA_SYS_REQ_IND,GKRSVBA_ACTIVITY_DATE,GKRSVBA_USER_ID,GKRSVBA_SURROGATE_ID,GKRSVBA_VERSION,GKRSVBA_DATA_ORIGIN,GKRSVBA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_A','GBA037_2_TERM',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSVBA (GKRSVBA_SQPR_CODE,GKRSVBA_SVBA_CODE,GKRSVBA_SQPA_CODE,GKRSVBA_DEFAULT_VALUE,GKRSVBA_SYS_REQ_IND,GKRSVBA_ACTIVITY_DATE,GKRSVBA_USER_ID,GKRSVBA_SURROGATE_ID,GKRSVBA_VERSION,GKRSVBA_DATA_ORIGIN,GKRSVBA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_A','GBA037_3_CAMP',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSVBA (GKRSVBA_SQPR_CODE,GKRSVBA_SVBA_CODE,GKRSVBA_SQPA_CODE,GKRSVBA_DEFAULT_VALUE,GKRSVBA_SYS_REQ_IND,GKRSVBA_ACTIVITY_DATE,GKRSVBA_USER_ID,GKRSVBA_SURROGATE_ID,GKRSVBA_VERSION,GKRSVBA_DATA_ORIGIN,GKRSVBA_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_A','GBA037_4_TIPO',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);


--ASIGNA PAR�METROS A REGLA
Insert into GKRSQRP (GKRSQRP_SQPR_CODE,GKRSQRP_SQRU_CODE,GKRSQRP_SQPA_CODE,GKRSQRP_DEFAULT_VALUE,GKRSQRP_SYS_REQ_IND,GKRSQRP_ACTIVITY_DATE,GKRSQRP_USER_ID,GKRSQRP_SURROGATE_ID,GKRSQRP_VERSION,GKRSQRP_DATA_ORIGIN,GKRSQRP_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_R','GBA037_1_ID',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQRP (GKRSQRP_SQPR_CODE,GKRSQRP_SQRU_CODE,GKRSQRP_SQPA_CODE,GKRSQRP_DEFAULT_VALUE,GKRSQRP_SYS_REQ_IND,GKRSQRP_ACTIVITY_DATE,GKRSQRP_USER_ID,GKRSQRP_SURROGATE_ID,GKRSQRP_VERSION,GKRSQRP_DATA_ORIGIN,GKRSQRP_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_R','GBA037_2_TERM',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQRP (GKRSQRP_SQPR_CODE,GKRSQRP_SQRU_CODE,GKRSQRP_SQPA_CODE,GKRSQRP_DEFAULT_VALUE,GKRSQRP_SYS_REQ_IND,GKRSQRP_ACTIVITY_DATE,GKRSQRP_USER_ID,GKRSQRP_SURROGATE_ID,GKRSQRP_VERSION,GKRSQRP_DATA_ORIGIN,GKRSQRP_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_R','GBA037_3_CAMP',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);
Insert into GKRSQRP (GKRSQRP_SQPR_CODE,GKRSQRP_SQRU_CODE,GKRSQRP_SQPA_CODE,GKRSQRP_DEFAULT_VALUE,GKRSQRP_SYS_REQ_IND,GKRSQRP_ACTIVITY_DATE,GKRSQRP_USER_ID,GKRSQRP_SURROGATE_ID,GKRSQRP_VERSION,GKRSQRP_DATA_ORIGIN,GKRSQRP_VPDI_CODE) VALUES ('GBA037_MDUU','GBA037_MDUU_R','GBA037_4_TIPO',NULL,'N',SYSDATE-1,'SAISUSR',NULL,NULL,NULL,NULL);


--CONSTRUTOR DE REGLAS DE NEGOCIOS SQL
DECLARE
	V_GKRRSQL_WHERE_CLAUSE CLOB;
	V_GKRRSQL_PARSED_SQL CLOB;
	V_ROWID VARCHAR2(20) DEFAULT NULL;
BEGIN

	Insert into GKRRSQL (GKRRSQL_SQPR_CODE,GKRRSQL_SQRU_CODE,GKRRSQL_SEQ_NO,GKRRSQL_ACTIVE_IND,GKRRSQL_VALIDATED_IND,GKRRSQL_START_DATE,GKRRSQL_SELECT_FROM,GKRRSQL_ACTIVITY_DATE,GKRRSQL_USER_ID,GKRRSQL_SELECT_VALUE,GKRRSQL_END_DATE,GKRRSQL_SURROGATE_ID,GKRRSQL_VERSION,GKRRSQL_DATA_ORIGIN,GKRRSQL_VPDI_CODE)
	values ('GBA037_MDUU','GBA037_MDUU_R','1','Y','Y',SYSDATE-1,'FROM',SYSDATE-1,'SAISUSR','SELECT',null,null,null,null,null);

	SELECT
		RSQL.ROWID
	INTO
		V_ROWID
	FROM
		GKRRSQL RSQL
	WHERE
		RSQL.GKRRSQL_SQPR_CODE = 'GBA037_MDUU'
	AND RSQL.GKRRSQL_SQRU_CODE = 'GBA037_MDUU_R'
	AND RSQL.GKRRSQL_SEQ_NO =
	(
		SELECT
			MAX(X.GKRRSQL_SEQ_NO)
		FROM
			GKRRSQL X
		WHERE
			X.GKRRSQL_SQPR_CODE = RSQL.GKRRSQL_SQPR_CODE
		AND X.GKRRSQL_SQRU_CODE = RSQL.GKRRSQL_SQRU_CODE
	);

	UPDATE
		GKRRSQL RSQL
	SET
		RSQL.GKRRSQL_WHERE_CLAUSE = 'SELECT 1 FROM DUAL'
		,RSQL.GKRRSQL_PARSED_SQL = 'SELECT 1 FROM DUAL'
	WHERE
		RSQL.ROWID = V_ROWID;

END;
/
--DEFINICI�N DE CONJUNTOS DE REGLAS PARA EL PROCESO
Insert into GKRPRST (GKRPRST_SQPR_CODE,GKRPRST_PRST_CODE,GKRPRST_SQRU_CODE,GKRPRST_SEQNO,GKRPRST_ACTIVE_IND,GKRPRST_ACTIVITY_DATE,GKRPRST_USER_ID,GKRPRST_SURROGATE_ID,GKRPRST_VERSION,GKRPRST_DATA_ORIGIN,GKRPRST_VPDI_CODE)
values ('GBA037_MDUU','GBA037_MDUU_RS','GBA037_MDUU_R','1','Y',SYSDATE-1,'SAISUSR',null,null,null,null);

-- DEFINICI�N DE CONJUNTOS DE REGLAS PARA EL PROCESO
Insert into GKRPACT (GKRPACT_SQPR_CODE,GKRPACT_PRST_CODE,GKRPACT_SVBA_CODE,GKRPACT_ACTIVE_IND,GKRPACT_ACTIVITY_DATE,GKRPACT_USER_ID,GKRPACT_SEQNO,GKRPACT_SURROGATE_ID,GKRPACT_VERSION,GKRPACT_DATA_ORIGIN,GKRPACT_VPDI_CODE)
values ('GBA037_MDUU','GBA037_MDUU_RS','GBA037_MDUU_A','Y',SYSDATE-1,'SAISUSR','1',null,null,null,null);

--create synonym "PUBLIC".SB_CALCULO_SEG_TER_MATRICULA for "SB_CALCULO_SEG_TER_MATRICULA";

commit;
